"""
Django settings for djangoproj project.

Generated by 'django-admin startproject' using Django 3.2.5.
"""

import os
from pathlib import Path

# BASE_DIR points to: /.../django-dealership-capstone/server
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-ccow$tz_=9%dxu4(0%^(z%nx32#s@(zt9$ih@)5l54yny)wm-0'
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    'saraximenagi-8000.theianext-0-labs-prod-misc-tools-us-east-0.proxy.cognitiveclass.ai'
]

CSRF_TRUSTED_ORIGINS = [
    'https://*.proxy.cognitiveclass.ai',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [],
}

INSTALLED_APPS = [
    'djangoapp.apps.DjangoappConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'djangoproj.urls'

# ---- Paths (frontend is inside server/) ----
FRONTEND_DIR = BASE_DIR / "frontend"
FRONTEND_STATIC_DIR = FRONTEND_DIR / "static"
FRONTEND_BUILD_DIR = FRONTEND_DIR / "build"
FRONTEND_BUILD_STATIC_DIR = FRONTEND_BUILD_DIR / "static"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            str(FRONTEND_BUILD_DIR),        # index.html exists here
            str(FRONTEND_STATIC_DIR),       # Home.html/About.html/Contact.html exist here
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangoproj.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# -------------------------
# Static / Media
# -------------------------
STATIC_URL = '/static/'

# Static source directories (what you already have)
STATICFILES_DIRS = [
    str(FRONTEND_STATIC_DIR),
    str(FRONTEND_BUILD_STATIC_DIR),
]

# collectstatic output (separate output folder)
STATIC_ROOT = str(BASE_DIR / "staticfiles")

MEDIA_ROOT = os.path.join(STATIC_ROOT, 'media')
MEDIA_URL = '/media/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
